//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinealCutOptimizer.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class BarPattern
    {
        public int Id { get; set; }
        public string Diameter { get; set; }
        public decimal Length { get; set; }
        public decimal MinLengthReusable { get; set; }
    }
}
